//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextOverflowStrategyType) DeepCopyInto(out *ContextOverflowStrategyType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextOverflowStrategyType.
func (in *ContextOverflowStrategyType) DeepCopy() *ContextOverflowStrategyType {
	if in == nil {
		return nil
	}
	out := new(ContextOverflowStrategyType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackConfig) DeepCopyInto(out *FallbackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackConfig.
func (in *FallbackConfig) DeepCopy() *FallbackConfig {
	if in == nil {
		return nil
	}
	out := new(FallbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackStrategyType) DeepCopyInto(out *FallbackStrategyType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackStrategyType.
func (in *FallbackStrategyType) DeepCopy() *FallbackStrategyType {
	if in == nil {
		return nil
	}
	out := new(FallbackStrategyType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMProvider) DeepCopyInto(out *LLMProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMProvider.
func (in *LLMProvider) DeepCopy() *LLMProvider {
	if in == nil {
		return nil
	}
	out := new(LLMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMProviderList) DeepCopyInto(out *LLMProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LLMProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMProviderList.
func (in *LLMProviderList) DeepCopy() *LLMProviderList {
	if in == nil {
		return nil
	}
	out := new(LLMProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMProviderSpec) DeepCopyInto(out *LLMProviderSpec) {
	*out = *in
	out.APIKeyRef = in.APIKeyRef
	if in.BlacklistModels != nil {
		in, out := &in.BlacklistModels, &out.BlacklistModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ModelConfigs != nil {
		in, out := &in.ModelConfigs, &out.ModelConfigs
		*out = make(map[string]ModelConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMProviderSpec.
func (in *LLMProviderSpec) DeepCopy() *LLMProviderSpec {
	if in == nil {
		return nil
	}
	out := new(LLMProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMProviderStatus) DeepCopyInto(out *LLMProviderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMProviderStatus.
func (in *LLMProviderStatus) DeepCopy() *LLMProviderStatus {
	if in == nil {
		return nil
	}
	out := new(LLMProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfig) DeepCopyInto(out *ModelConfig) {
	*out = *in
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(FallbackConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfig.
func (in *ModelConfig) DeepCopy() *ModelConfig {
	if in == nil {
		return nil
	}
	out := new(ModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}
